services:
    nginx:
        container_name: trivia-nginx
        image: nginx:1.23-alpine
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/app
        ports:
            - 80:80
    php:
        container_name: trivia-php
        build: ./docker/php
        working_dir: /app
        volumes:
            - ./src:/app
        env_file:
           - .env
    mariadb:
        container_name: trivia-mariadb
        image: mariadb:10.0
        env_file:
           - .env
        volumes:
            - ./docker/mysql/data/mariadb:/var/lib/mysql
        ports:
            - 3306:3306